DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS quizzes CASCADE;
DROP TABLE IF EXISTS questions CASCADE;
DROP TABLE IF EXISTS options CASCADE;

CREATE TABLE users(
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(50)
);

CREATE TABLE quizzes(
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR(255),
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE questions (
  id SERIAL PRIMARY KEY NOT NULL,
  question_string TEXT NOT NULL,
  correct_option_id REFERENCES options(id) ON DELETE CASCADE,
);

CREATE TABLE options (
  id SERIAL PRIMARY KEY NOT NULL,
  question_id INTEGER REFERENCES questions(id) ON DELETE CASCADE,
  content TEXT NOT NULL
);
